version: '2'
services:
  web:
    image: tomcat:8
    ports:
      - "80:8080"
    volumes:
      - data_volume:/opt
    depends_on:
      - maven

  maven:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .data_volume:/tmp/opt
volumes:
  data_volume:
