version: '2'
services:
  web:
    container_name: web
    image: tomcat:8
    ports:
      - "80:8080"
    volumes:
      - data_volume:/usr/local/tomcat/webapps
    depends_on:
      - maven

  maven:
    container_name: construct
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data_volume:/boxfuse-sample-java-war-hello/target/
volumes:
  data_volume:
