version: '2'
services:
  web:
    image: tomcat:8
    ports:
      - "80:8080"
    volumes_from:
      - maven:rw
  maven:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/data
